# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

$mainMod = SUPER
$terminal = alacritty
$fileManager = thunar
$menu = hyprlauncher

# --- APPS & SYSTEM ---
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod SHIFT, V, exec, cliphist list | rofi -dmenu -theme cyber_clean | cliphist decode | wl-copy
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod, W, exec, python /home/ishanmanisingh/.config/hypr/scripts/code7x_gallery.py
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, T, exec, rofi -show emoji -theme emoji_grid
bind = $mainMod, K, exec, /home/ishanmanisingh/.config/hypr/scripts/rofi-kill.sh
bind = $mainMod, U, exec, pkill -USR2 -f code7x_sidebar.py

# --- SCREENSHOTS ---
bind = , Print, exec, mkdir -p ~/Pictures/Screenshots && grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png | wl-copy
bind = SHIFT, Print, exec, mkdir -p ~/Pictures/Screenshots && grim ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png && notify-send "Screenshot Captured"

# --- WORKSPACES ---
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

bind = $mainMod, S, togglespecialworkspace
bind = $mainMod SHIFT, S, movetoworkspace, special
bind = $mainMod, F, fullscreen

# --- MOUSE BINDINGS ---
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# --- AUTOSTART ---
exec-once = python3 /home/ishanmanisingh/.config/hypr/scripts/code7x_sidebar.py
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = waybar
exec-once = hypridle
exec-once = nm-applet
exec-once = ~/.config/hypr/scripts/wallpaper-start.sh
exec-once = ~/.config/hypr/scripts/wallpaper-rotate.sh
exec-once = nohup awww-daemon >/dev/null 2>&1 &
exec-once = bash -c 'sleep 2 && awww img "$(find ~/Wallpapers -type f | shuf -n 1)"'

# --- DECORATION ---
decoration {
    rounding = 16
    blur {
        enabled = true
        size = 8
        passes = 3
    }
    shadow {
        enabled = true
    }
}


